INSERT INTO CUSTOMERS (NAMESURNAME,BIRTHDATE,CITY) VALUES('AHMET COSKUN','11.11.1980','ISTANBUL')
INSERT INTO CUSTOMERS (NAMESURNAME,BIRTHDATE,CITY) VALUES('MUSTAFA ERDEMLI','11.11.1980','ANKARA')
INSERT INTO CUSTOMERS (NAMESURNAME,BIRTHDATE,CITY) VALUES('OMER COLALOGLU','11.11.1980','IZMIR')
INSERT INTO CUSTOMERS (NAMESURNAME,BIRTHDATE,CITY) VALUES('ZEYNEP ARSLAN','11.11.1980','BURSA')
INSERT INTO CUSTOMERS (NAMESURNAME,BIRTHDATE,CITY) VALUES('EMINE TURNA','11.11.1980','ADANA')
INSERT INTO CUSTOMERS (NAMESURNAME,BIRTHDATE,CITY) VALUES('BERKAY KAYA','11.11.1980','BALIKESIR')

INSERT INTO CUSTOMERS (NAMESURNAME,BIRTHDATE,CITY) VALUES('AYSE DENIZ','19801111','ISTANBUL')

SELECT * FROM CUSTOMERS

INSERT INTO CUSTOMERS (NAMESURNAME,BIRTHDATE,CITY) VALUES('COSKUN DEMIR','19801111','BURSA')

UPDATE CUSTOMERS SET NAMESURNAME='OMER COLAKOGLU' WHERE ID=4

UPDATE CUSTOMERS SET BIRTHDATE='19801211'